#!/usr/bin/perl
#
# revtool -- Source Code Revision Control Tool
# 
# Copyright (C) 2001, Michael Jennings
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies of the Software, its documentation and marketing & publicity
# materials, and acknowledgment shall be given in the documentation, materials
# and software packages that this Software was used.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# $Id: revtool,v 1.83 2004/06/22 23:10:07 mej Exp $
#

use strict;
use Getopt::Long;
use Mezzanine::Util;
#use Mezzanine::RevCtl;
use Mezzanine::SCM;
use Mezzanine::Config;

my $config;

# Print usage information
sub
print_usage_info
{
    my ($leader, $underbar);

    print "\n";
    $leader = "$PROGNAME $VERSION Usage Information";
    $underbar = $leader;
    $underbar =~ s/./-/g;
    print "$leader\n$underbar\n";
    print "\n";
    print "  Syntax:   $PROGNAME [ options ] [ files ]\n";
    print "\n";
    print "    -h --help                Show this usage information\n";
    print "    -d --debug               Turn on debugging\n";
    print "    -v --version             Show version and copyright\n";
    print "    -g --get                 Download and/or merge the current sources from the master tree\n";
    print "    -p --put                 Upload new changes to the master tree\n";
    print "    -a --add                 Mark new files for addition into the master tree\n";
    print "    -r --remove              Delete files and mark them for deletion in the master tree\n";
    print "    -q --query <type>        Query for a particular type of information\n";
    print "    -i --import              Import a new set of sources, or update the vendor branch for a package\n";
    print "    -t --tag <tag>           Specify a symbolic tag for an operation, or tag local sources\n";
    print "    -T --rtag <tag>          Tag one or more complete modules directly\n";
    print "    -b --branch              When performing a tag, make it a branch tag\n";
    print "    -l --login               Perform a login to the repository\n";
    print "    -R --recurse             Operate recursively (this is the default for some commands)\n";
    print "    -k [code]                Specify keyword handling when adding files (use -kb to add binary files)\n";
    print "    -D --dir                 Specify an alternative repository (\$REPOSITORY)\n";
    print "    -x --exclusive           Only commit the specified files\n";
    print "       --reset               Reset sticky tags, dates, etc. in the current module\n";
    print "       --blind               Do not update before committing (may result in conflicts, use carefully)\n";
    print "\n";
    exit(0);
}

# main() here is basically the same as main() in C
sub
main
{
    my ($scm, $mode, $retval);

    &mezz_init("revtool", "3.0", "help|h", "version|v", "debug|d",
               "get|g", "put|p", "add|a", "remove|r", "query|q=s",
               "recurse|R!", "tag|source-tag|t=s", "import|i",
               "info|query|I", "diff", "stat|status", "log",
               "annotate|ann|blame", "keyword|k=s", "dir|D=s",
               "exclusive|x!", "init", "ttag|target-tag|T=s",
               "login|l!", "branch|b!", "reset!", "blind!",
               "message|m=s", "protocol|P=s", "init", "savecfg!");

    if ($OPTION{"version"}) {
        &print_version($PROGNAME, $VERSION, "Michael Jennings <mej\@eterm.org>",
                       'CVS Revision $Revision: 1.83 $ created on $Date: 2004/06/22 23:10:07 $ by $Author: mej $ ');
    }
    if ($OPTION{"help"}) {
	&print_usage_info();
    }
    open(STDERR, ">&STDOUT");
    $config = Mezzanine::Config->new("scm/config");
    if (!scalar($config->keys())) {
        $OPTION{"savecfg"} = 1;
    }

    # Set basic options
    &debug_set($config->set("DEBUG", $OPTION{"debug"} || $config->get("DEBUG") || 0));
    $config->set("PROTOCOL", $OPTION{"protocol"} || $config->get("PROTOCOL"));
    if ($config->get("PROTOCOL")) {
        $scm = Mezzanine::SCM::new($config->get("PROTOCOL"));
    } elsif (scalar(@ARGV) && -d $ARGV[0]) {
        $scm = Mezzanine::SCM::auto_detect($ARGV[0]);
    } else {
        $scm = Mezzanine::SCM::auto_detect('.');
    }

    # Set the mode, first based on executable name...
    if ($0 =~ /(get|co|checkout)$/) {
        $mode = "get";
        $OPTION{"get"} = 1;
    } elsif ($0 =~ /(put|ci|commit|checkin)$/) {
        $mode = "put";
        $OPTION{"put"} = 1;
    } elsif ($0 =~ /import$/) {
        $mode = "import";
    } elsif ($0 =~ /(ask|query|info)$/) {
        $mode = "info";
    } elsif ($0 =~ /diff$/) {
	$mode = "diff";
    } elsif ($0 =~ /stat(us)?$/) {
	$mode = "status";
    } elsif ($0 =~ /log$/) {
	$mode = "log";
    } elsif ($0 =~ /(ann|annotate|blame)$/) {
	$mode = "annotate";
    } elsif ($0 =~ /(add|new)$/) {
        $mode = "add";
        $OPTION{"add"} = 1;
    } elsif ($0 =~ /(rm|remove|kill|nuke|purge)$/) {
        $mode = "remove";
        $OPTION{"remove"} = 1;
    } elsif ($0 =~ /(tag|label|mark)$/) {
        $mode = "tag";
    } elsif ($0 =~ /reset$/) {
        $mode = "reset";
        $OPTION{"reset"} = 1;
    } elsif ($0 =~ /init$/) {
        $mode = "init";
    } elsif ($0 =~ /login$/) {
        $mode = "login";
    # ...then on command line options
    } elsif ($OPTION{"import"}) {
        $mode = "import";
    } elsif ($OPTION{"put"}) {
        $mode = "put";
    } elsif ($OPTION{"get"}) {
        $mode = "get";
    } elsif ($OPTION{"add"}) {
        $mode = "add";
    } elsif ($OPTION{"remove"}) {
        $mode = "remove";
    } elsif ($OPTION{"diff"}) {
        $mode = "diff";
    } elsif ($OPTION{"info"}) {
        $mode = "info";
    } elsif ($OPTION{"stat"}) {
        $mode = "stat";
    } elsif ($OPTION{"log"}) {
        $mode = "log";
    } elsif ($OPTION{"annotate"}) {
        $mode = "annotate";
    } elsif ($OPTION{"tag"}) {
        $mode = "tag";
    } elsif ($OPTION{"merge"}) {
        $mode = "merge";
    } elsif ($OPTION{"branch"}) {
        $mode = "branch";
    } elsif ($OPTION{"reset"}) {
        $mode = "reset";
    } elsif ($OPTION{"init"}) {
        $mode = "init";
    } elsif ($OPTION{"login"}) {
        $mode = "login";
    }

    $scm->propset(
                  "repository" => $OPTION{"dir"},
                  "keyword_expansion" => $OPTION{"keyword"},
                  "recursion" => $OPTION{"recurse"},
                  "reset" => $OPTION{"reset"},
                  "source_tag" => $OPTION{"tag"},
                  "target_tag" => $OPTION{"ttag"}
                 );
    if (defined($OPTION{"exclusive"})) {
        if ($mode eq "import") {
            $scm->propset("use_standard_ignore", $OPTION{"exclusive"});
        } elsif (scalar(@ARGV)) {
            $scm->propset("args_only", $OPTION{"exclusive"});
        } else {
            $scm->propset("update_changelog", $OPTION{"exclusive"});
        }
    }

    if ($OPTION{"login"}) {
        $scm->login();
        return if ($mode eq "login");
    }
    if ($mode eq "import") {
        $scm->imprt(@ARGV);
    } elsif ($mode eq "diff") {
        $scm->diff(@ARGV);
    } elsif ($mode eq "annotate") {
        $scm->annotate(@ARGV);
    } elsif ($mode eq "info") {
        $scm->info(@ARGV);
    } elsif ($mode eq "status") {
        $scm->status(@ARGV);
    } elsif ($mode eq "log") {
        $scm->log(@ARGV);
    } elsif ($mode eq "tag") {
        if ((! $scm->propget("source_tag")) || (!length($scm->propget("source_tag")))) {
            $scm->propset("source_tag", (shift @ARGV));
        }
        $scm->tag(@ARGV);
    } else {
        if ($OPTION{"add"}) {
            $scm->add(@ARGV);
            if (! $OPTION{"exclusive"}) {
                @ARGV = ();
            }
        } elsif ($OPTION{"remove"}) {
            $scm->remove(@ARGV);
            if (! $OPTION{"exclusive"}) {
                @ARGV = ();
            }
        }
        if (($mode eq "get") || ($scm->propget("reset"))) {
            $retval = $scm->get(@ARGV);
        } elsif ($mode eq "put") {
            if (! $OPTION{"blind"}) {
                $retval = $scm->get(@ARGV);
                if ($retval != MEZZANINE_SUCCESS) {
                    eprint "Get failed; aborting put process.\n";
                    return $retval;
                }
            }
            $retval = $scm->put($OPTION{"message"}, @ARGV);
        }
    }
    return $retval;
}

exit &main();
