.TH REVTOOL 1  "28 Jul 2000" "2000"
.SH NAME
revtool - the application that handles all interaction with the revision control system. 
.SH SYNOPSIS
.B revtool
.RI [ options ]

.SH DESCRIPTION
.PP
.B revtool 
\(em version
.B 1.0 
\(em encapsulates all revision-control-system-specific
commands and gives them an interface which is independent of the
underlying system.  Thus, if the repository was moved from CVS to,
say, BitKeeper, revtool's code would change, but its interface would
remain the same. 
.SH OPTIONS
The
.B revtool 
options are listed below.
.LP
.TP
.BR "\-h" , " \-\-help"
Print out a message describing available options. 
.TP
.BR "\-d" , " \-\-debug" 
Turn on debugging 
.TP
.BR "\-v" , " \-\-version" 
Show version and copyright
.TP
.BR "\-g" , " \-\-get"
Download and/or merge the current sources from the master tree
.TP
.BR "\-p" , " \-\-put"
Upload new changes to the master tree
.TP
.BR "\-r" , " \-\-remove"
Delete files and mark them for deletion in the master tree
.TP
.BI \-q " type" ", \-\-query " type 
Query for a particular type of information
.TP
.BR "\-i" , " \-\-import"
Import a new set of sources, or update the vendor branch for a package
.TP
.BI \-T " tag" ", \-\-rtag " tag 
Tag one or more complete modules directly
.TP
.BI \-t " tag" ",  \-\-tag " tag
Specify a symbolic tag for an operation, or tag local sources
.TP
.BR "\-l" , " \-\-login"
Perform a login to the repository
.TP
.BR "\-R" , " \-\-recurse"
Operate recursively (this is the default for some commands)
.TP
.BI \-k " code" 
Specify keyword handling when adding files (use -kb to add binary files)
.TP
.BR "\-D" , " \-\-dir" 
Specify an alternative repository ($CVSROOT)
.TP
.BR "\-x" , " \-\-exclusive"
Only commit the specified files
.TP
.BI \-\-addlist " files 
Specify which files to add so that adds and removes can coincide
.TP
.BI \-\-remlist " files                  
Specify which files to remove so that ds and removes can coincide
.SH AUTHORS
Michael Jennings (mej@valinux.com).  
Man page written by ccr (ccr@valinux.com).

.SH MORE INFORMATION
A detailed description of buildtool functionality is available
in the README.
