#!/bin/sh -x
#
# web-sync - Resync engr web site with latest sources
#
# Michael Jennings <mej@valinux.com>
# 28 Sept 2000
#
# $Id: web-sync,v 1.8 2001/02/07 22:04:49 mej Exp $
#

if [ ! -z "$SUDO_USER" ]; then
  USER=$SUDO_USER
elif [ "x$USER" = "x" ]; then
  USER=`whoami`
fi

SCP_CMD="scp -C"
RSYNC_CMD="rsync -av --exclude=CVS --exclude=.cvsignore --exclude=.buildtool.symlinks --delete --delete-excluded"
CHOWN_CMD="chown -R $USER:engr"
CHMOD_CMD="chmod -R ug+w,a+r"

if [ "x$1" = "x" ]; then
  echo "Usage:  `/bin/basename $0` <version> [ <version> ... ]"
  exit -1
fi

for i in $* ; do
  case $i in
    6.2.*)
      REMOTE_UHOST=mej@grendel
      REMOTE_DIR=/md/6.2/home/mej/avalon/build
      LOCAL_DIR=/home/ftp/pub/VALinux
      for j in os powertools ; do
        mkdir -p $LOCAL_DIR/$i/$j
        cd $LOCAL_DIR/$i/$j
        echo "*** Synchronizing $j ***"
        mkdir -p $LOCAL_DIR/$i/$j/cd
        $RSYNC_CMD $REMOTE_UHOST:$REMOTE_DIR/va-$j-rpms/ $LOCAL_DIR/$i/$j/cd/
        echo "*** Copying ISO images ***"
        mkdir -p $LOCAL_DIR/$i/$j/iso
        $RSYNC_CMD $REMOTE_UHOST:$REMOTE_DIR/va-redhat-$j-'*'.iso $LOCAL_DIR/$i/$j/iso/
        echo "*** Creating RPMS directory ***"
        mkdir -p $LOCAL_DIR/$i/$j/RPMS
        rm -f RPMS/*.rpm
        (cd cd ; find . \( -name '*.rpm' -a ! -name '*src.rpm' \) -exec cp -a {} ../RPMS/ \;)
        echo "*** Creating SRPMS directory ***"
        mkdir -p $LOCAL_DIR/$i/$j/SRPMS
        if [ "$j" = "os" ]; then
            $RSYNC_CMD $REMOTE_UHOST:$REMOTE_DIR/va-$j-srpms/SRPMS/ $LOCAL_DIR/$i/$j/SRPMS/
        else
            $RSYNC_CMD $REMOTE_UHOST:$REMOTE_DIR/va-$j-srpms/Powertools/SRPMS/ $LOCAL_DIR/$i/$j/SRPMS/
        fi
        echo "*** Fixing ownerships and permissions ***"
        $CHOWN_CMD RPMS SRPMS iso
        $CHMOD_CMD RPMS SRPMS iso
      done
      echo "*** Sync of $i done ***"
      ;;

    7.0.1)
      REMOTE_UHOST=mej@grendel
      REMOTE_DIR=/md/7.0/home/mej/avalon/build
      LOCAL_DIR=/home/ftp/pub/VALinux
      mkdir -p $LOCAL_DIR/$i
      cd $LOCAL_DIR/$i
      echo "*** Synchronizing network install image ***"
      mkdir -p $LOCAL_DIR/$i/os/image
      $RSYNC_CMD $REMOTE_UHOST:$REMOTE_DIR/va-redhat-7.0-net/ $LOCAL_DIR/$i/os/image/
      echo "*** Copying ISO images ***"
      mkdir -p $LOCAL_DIR/$i/os/iso
      $SCP_CMD $REMOTE_UHOST:$REMOTE_DIR/va-redhat-os-'*'.iso $LOCAL_DIR/$i/os/iso/
      echo "*** Synchronizing extras ***"
      mkdir -p $LOCAL_DIR/$i/extras/image
      $RSYNC_CMD $REMOTE_UHOST:$REMOTE_DIR/va-redhat-7.0-extras/ $LOCAL_DIR/$i/extras/image/
      echo "*** Copying ISO images ***"
      mkdir -p $LOCAL_DIR/$i/extras/iso
      $SCP_CMD $REMOTE_UHOST:$REMOTE_DIR/va-redhat-extras-'*'.iso $LOCAL_DIR/$i/extras/iso/
      for j in RPMS SRPMS ; do
        echo "*** Synchronizing $j ***"
        mkdir -p $LOCAL_DIR/$i/$j
        $RSYNC_CMD $REMOTE_UHOST:$REMOTE_DIR/va-redhat-7.0-www/$j/ $LOCAL_DIR/$i/$j/
      done
      echo "*** Fixing ownerships and permissions ***"
      $CHOWN_CMD RPMS SRPMS os/iso extras/iso
      $CHMOD_CMD RPMS SRPMS os/iso extras/iso
      echo "*** Sync of $i done ***"
      ;;

  esac
done
