.TH AVALON 1  "09 MAY 2001" "AVALON(1)"
.SH NAME
avalon - VA Linux software management and build environment. 
.SH DESCRIPTION
.PP
.B Avalon 
is a suite of programs that, when used correctly, can build
an operating system from source.  
.B Avalon
is comprised of several tools:
.LP
.TP
.BR buildtool
Product Build Management Tool
.TP
.BR compstool
Tool for verifying the integrity of comps files
.TP
.BR imgtool
Tool for generating disk images from package lists
.TP
.BR mediatool
Tool for generating disk images, CD's, etc.
.TP
.BR pkgsort
Tool for sorting package lists
.TP
.BR pkgtool
Tool for generating source/patch files from a source code repository
.TP
.BR revtool
Source Code Revision Control Tool
.TP
.BR srctool
Source maintenance utility

.SH Shortcuts
As each of these tools provide several features, Avalon provides
"helper" apps that isolates individual features.

.LP
.TP 
.BR avget, avco
Download and/or merge the current sources from the master tree
(revtool --get)
.TP
.BR avput, avci
Upload new changes to the master tree
(revtool --put)
.TP
.BR avadd, avnew
Mark new files for addition into the master tree
(revtool --add)
.TP
.BR avremove, avrm, avkill, avnuke, avpurge
Delete files and mark them for deletion in the master tree
(revtool --remove)
.TP
.BR avquery, avask, avinfo
Query for a particular type of information
(revtool --query)
.TP
.BR avimport
Import a new set of sources, or update the vendor branch for a package
(revtool --import)
.TP
.BR avrtag  
Tag one or more complete modules directly 
(revtool --rtag)
.TP
.BR avtag
Specify a symbolic tag for an operation, or tag local sources 
(revtool --tag)
.TP
.BR avlogin
Login to the repository 
(revtool --login)
.TP
.BR avreset
Reset sticky tags, dates, etc. in the current module 
(revtool --reset)
.TP
.BR avdiff
Generate diff between repository and current working directory
(revtool -qd)
.TP
.BR avlog
Show the commit log for file(s)
(revtool -ql)
.TP
.BR avstatus
Show the current status of working tree
(revtool -qs)
.TP
.BR avbuild
Same as buildtool
.TP
.BR avimport
Import a new package/source tree 
(srctool --import)
.TP
.BR avprep
Prepare a working tree 
(srctool --prepare)
.TP
.BR avmerge
Merge one or more raw files into an SPM 
(srctool --merge)
.TP
.BR avpatch
Apply changes in the working tree as a patch to the SPM 
(srctool --apply)
.TP
.BR avmod
Upload modifications to the master repository 
(srctool --modify)
.TP
.BR avpkg
Same as pkgtool
.TP
.BR avrpm
Same as pkgtool

.SH AUTHORS
Michael Jennings (mej@valinux.com).  
Man page written by Walt Drummond (drummond@valinux.com).
