.TH MEZZANINE 1  "09 MAY 2001" "MEZZANINE(1)" "MEZZANINE"
.SH NAME
mezzanine - VA Linux software management and build environment. 
.SH DESCRIPTION
.PP
.B Mezzanine 
is a suite of programs that, when used correctly, can build
an operating system from source.  
.B Mezzanine
is comprised of several tools:
.LP
.TP
.BR buildtool
Product Build Management Tool
.TP
.BR compstool
Tool for verifying the integrity of comps files
.TP
.BR imgtool
Tool for generating disk images from package lists
.TP
.BR mediatool
Tool for generating disk images, CD's, etc.
.TP
.BR pkgsort
Tool for sorting package lists
.TP
.BR pkgtool
Tool for generating source/patch files from a source code repository
.TP
.BR revtool
Source Code Revision Control Tool
.TP
.BR srctool
Source maintenance utility

.SH Shortcuts
As each of these tools provide several features, Mezzanine provides
"helper" apps that isolates individual features.

.LP
.TP 
.BR mzget, mzco
Download and/or merge the current sources from the master tree
(revtool --get)
.TP
.BR mzput, mzci
Upload new changes to the master tree
(revtool --put)
.TP
.BR mzadd, mznew
Mark new files for addition into the master tree
(revtool --add)
.TP
.BR mzremove, mzrm, mzkill, mznuke, mzpurge
Delete files and mark them for deletion in the master tree
(revtool --remove)
.TP
.BR mzquery, mzask, mzinfo
Query for a particular type of information
(revtool --query)
.TP
.BR mzimport
Import a new set of sources, or update the vendor branch for a package
(revtool --import)
.TP
.BR mzrtag  
Tag one or more complete modules directly 
(revtool --rtag)
.TP
.BR mztag
Specify a symbolic tag for an operation, or tag local sources 
(revtool --tag)
.TP
.BR mzlogin
Login to the repository 
(revtool --login)
.TP
.BR mzreset
Reset sticky tags, dates, etc. in the current module 
(revtool --reset)
.TP
.BR mzdiff
Generate diff between repository and current working directory
(revtool -qd)
.TP
.BR mzlog
Show the commit log for file(s)
(revtool -ql)
.TP
.BR mzstatus
Show the current status of working tree
(revtool -qs)
.TP
.BR mzbuild
Same as buildtool
.TP
.BR mzimport
Import a new package/source tree 
(srctool --import)
.TP
.BR mzprep
Prepare a working tree 
(srctool --prepare)
.TP
.BR mzmerge
Merge one or more raw files into an SPM 
(srctool --merge)
.TP
.BR mzpatch
Apply changes in the working tree as a patch to the SPM 
(srctool --apply)
.TP
.BR mzmod
Upload modifications to the master repository 
(srctool --modify)
.TP
.BR mzpkg
Same as pkgtool
.TP
.BR mzrpm
Same as pkgtool

.SH AUTHORS
Michael Jennings (mej@kainx.org).  
Man page written by Walt Drummond (drummond@wfd3.com).
